/**
 * 2025-26 ATO individual-return label taxonomy (PRD §8).
 *
 * Item / label numbers and names, the myTax on-screen section order (so the
 * T20 export PDF can follow it), and the item-21 rental property schedule with
 * its full income + deduction sub-label list.
 *
 * Curated 2026-09-04 from the ATO "Individual tax return 2026 instructions",
 * the "Supplementary tax return 2026 instructions" (item 21 Rent), and the
 * "myTax 2026" instruction set. `inScope` reflects the current tool scope
 * (PRD §3 non-goals, §6 FR-4/FR-5/FR-24) — out-of-scope labels are listed so
 * detection (T9) and the export can name them.
 */
import type { LabelTaxonomy, MyTaxSection, ReturnLabel, RentalScheduleLabel } from "../types";

const SRC = {
  itr: "https://www.ato.gov.au/forms-and-instructions/individual-tax-return-2026-instructions",
  suppRent:
    "https://www.ato.gov.au/forms-and-instructions/individual-supplementary-tax-return-2026-instructions/income-questions-13-24-supplementary-tax-return-2026/21-rent-2026",
  mytax:
    "https://www.ato.gov.au/individuals-and-families/your-tax-return/instructions-to-complete-your-tax-return/mytax-instructions/2026",
} as const;

const MYTAX_SECTION_ORDER: readonly MyTaxSection[] = [
  "personalise",
  "income",
  "deductions",
  "tax-losses",
  "tax-offsets",
  "adjustments",
  "medicare-and-phi",
  "spouse-and-income-tests",
  "estimate",
];

const LABELS: readonly ReturnLabel[] = [
  // --- Personalise -------------------------------------------------------
  {
    code: "personalise.residency",
    name: "Were you an Australian resident for tax purposes for the full year?",
    section: "personalise",
    form: "main",
    inScope: true,
    note: "A 'no' (non-resident or part-year) is out of scope → FR-20.",
  },
  {
    code: "personalise.spouse",
    name: "Did you have a spouse at any time during the income year?",
    section: "personalise",
    form: "main",
    inScope: true,
  },

  // --- Income (main form) ----------------------------------------------
  {
    code: "1",
    name: "Salary or wages",
    section: "income",
    form: "main",
    inScope: true,
    note: "Per employer, with the payer's name and ABN carried through for the export.",
  },
  {
    code: "1.taxWithheld",
    name: "Tax withheld — salary or wages (PAYG)",
    section: "income",
    form: "main",
    inScope: true,
    note: "Per employer. Kept to the cent (FR-15).",
  },
  {
    code: "2",
    name: "Allowances, earnings, tips, directors fees etc",
    section: "income",
    form: "main",
    inScope: true,
    note: "Only allowances shown on the income statement / payment summary.",
  },
  {
    code: "5",
    name: "Australian Government allowances and payments",
    section: "income",
    form: "main",
    inScope: true,
    note: "Taxable working-age allowances — JobSeeker, Youth Allowance, Austudy. Drives the beneficiary tax offset.",
  },
  {
    code: "6",
    name: "Australian Government pensions and allowances",
    section: "income",
    form: "main",
    inScope: false,
    note: "Age Pension and other pensions are out of scope (SAPTO / seniors thresholds) → FR-20. Detected for scope only.",
  },
  {
    code: "10L",
    name: "Gross interest",
    section: "income",
    form: "main",
    inScope: true,
    note: "Apportioned to the taxpayer's share for joint accounts (FR-4).",
  },
  {
    code: "10M",
    name: "TFN amounts withheld from gross interest",
    section: "income",
    form: "main",
    inScope: true,
  },
  {
    code: "11S",
    name: "Dividends — unfranked amount",
    section: "income",
    form: "main",
    inScope: true,
  },
  {
    code: "11T",
    name: "Dividends — franked amount",
    section: "income",
    form: "main",
    inScope: true,
  },
  {
    code: "11U",
    name: "Dividends — franking credit",
    section: "income",
    form: "main",
    inScope: true,
    note: "Applied as a refundable tax offset (FR-11). Kept to the cent (FR-15).",
  },
  {
    code: "11V",
    name: "TFN amounts withheld from dividends",
    section: "income",
    form: "main",
    inScope: true,
  },
  {
    code: "13",
    name: "Partnerships and trusts",
    section: "income",
    form: "supplement",
    inScope: false,
    note: "Trust / partnership / managed-fund distributions are out of scope → FR-20.",
  },
  {
    code: "15",
    name: "Net income or loss from business",
    section: "income",
    form: "supplement",
    inScope: false,
    note: "Sole-trader / business income is out of scope → FR-20.",
  },
  {
    code: "18",
    name: "Capital gains",
    section: "income",
    form: "supplement",
    inScope: false,
    note: "CGT (incl. sale of the rental) is out of scope → FR-20.",
  },
  {
    code: "20",
    name: "Foreign source income and foreign assets or property",
    section: "income",
    form: "supplement",
    inScope: false,
    note: "Foreign income (incl. an overseas rental) is out of scope → FR-20.",
  },
  {
    code: "21",
    name: "Rent",
    section: "income",
    form: "supplement",
    inScope: true,
    note: "One solely-owned long-term residential property, let / available all year (FR-24). See rentalSchedule.",
  },

  // --- Deductions ------------------------------------------------------
  {
    code: "D1",
    name: "Work-related car expenses",
    section: "deductions",
    form: "main",
    inScope: true,
    note: "Cents-per-km method only, capped at the annual limit. The logbook method routes to FR-20.",
  },
  {
    code: "D2",
    name: "Work-related travel expenses",
    section: "deductions",
    form: "main",
    inScope: true,
  },
  {
    code: "D3",
    name: "Work-related clothing, laundry and dry-cleaning expenses",
    section: "deductions",
    form: "main",
    inScope: true,
  },
  {
    code: "D4",
    name: "Work-related self-education expenses",
    section: "deductions",
    form: "main",
    inScope: true,
  },
  {
    code: "D5",
    name: "Other work-related expenses",
    section: "deductions",
    form: "main",
    inScope: true,
    note: "Includes working from home by the fixed-rate method (hours record + rate). The actual-cost method routes to FR-20.",
  },
  {
    code: "D6",
    name: "Low-value pool deduction",
    section: "deductions",
    form: "main",
    inScope: false,
    note: "Not offered as a work-related deduction. Rental low-value pool amounts come from the QS schedule into the rental schedule.",
  },
  {
    code: "D7",
    name: "Interest deductions",
    section: "deductions",
    form: "main",
    inScope: false,
    note: "Out of scope → FR-20 (rental loan interest is item 21 label Q, not D7).",
  },
  {
    code: "D8",
    name: "Dividend deductions",
    section: "deductions",
    form: "main",
    inScope: false,
    note: "Out of scope → FR-20.",
  },
  {
    code: "D9",
    name: "Gifts or donations",
    section: "deductions",
    form: "main",
    inScope: true,
    note: "To deductible gift recipients, with a receipt.",
  },
  {
    code: "D10",
    name: "Cost of managing tax affairs",
    section: "deductions",
    form: "main",
    inScope: true,
  },
  {
    code: "D.total",
    name: "Total deductions",
    section: "deductions",
    form: "main",
    inScope: true,
    note: "Computed = sum of the deduction labels + total rental deductions.",
  },

  // --- Tax losses ----------------------------------------------------
  {
    code: "L1",
    name: "Tax losses of earlier income years",
    section: "tax-losses",
    form: "supplement",
    inScope: false,
    note: "Prior-year losses are out of scope → FR-20 / noted as an ATO-side unknown on the estimate.",
  },

  // --- Tax offsets --------------------------------------------------
  {
    code: "T1",
    name: "Seniors and pensioners tax offset (SAPTO)",
    section: "tax-offsets",
    form: "main",
    inScope: false,
    note: "Out of scope (pensions / seniors thresholds) → FR-20.",
  },
  {
    code: "T2",
    name: "Australian superannuation income stream tax offset",
    section: "tax-offsets",
    form: "main",
    inScope: false,
    note: "Super income streams are out of scope → FR-20.",
  },
  {
    code: "offset.lito",
    name: "Low income tax offset (LITO)",
    section: "tax-offsets",
    form: "main",
    inScope: true,
    note: "Non-refundable. Calculated automatically by the ATO; the engine computes it for the estimate.",
  },
  {
    code: "offset.beneficiary",
    name: "Beneficiary tax offset",
    section: "tax-offsets",
    form: "main",
    inScope: true,
    note: "Non-refundable. No manual label — driven by item 5 / item 6 amounts.",
  },
  {
    code: "offset.frankingCredits",
    name: "Franking credit tax offset",
    section: "tax-offsets",
    form: "main",
    inScope: true,
    note: "Refundable. From item 11 label U.",
  },
  {
    code: "offset.phiRebate",
    name: "Private health insurance rebate reconciliation",
    section: "tax-offsets",
    form: "main",
    inScope: true,
    note: "Reconciled from the PHI tax statement against the entitlement at the FR-23 rebate-tier income (FR-11). Also entered under 'Private health insurance policy details'.",
  },

  // --- Adjustments ------------------------------------------------
  {
    code: "A1",
    name: "Under 18",
    section: "adjustments",
    form: "main",
    inScope: false,
    note: "Minors' special rates not modelled in v1.",
  },
  {
    code: "A2",
    name: "Part-year tax-free threshold",
    section: "adjustments",
    form: "main",
    inScope: false,
    note: "Part-year residency is out of scope → FR-20.",
  },

  // --- Medicare & private health insurance --------------------
  {
    code: "M1",
    name: "Medicare levy reduction or exemption",
    section: "medicare-and-phi",
    form: "main",
    inScope: true,
    note: "Low-income reduction / shade-in (FR-9). Full exemption categories are limited in v1.",
  },
  {
    code: "M2",
    name: "Medicare levy surcharge",
    section: "medicare-and-phi",
    form: "main",
    inScope: true,
    note: "Applied only for days without adequate private hospital cover (FR-9).",
  },
  {
    code: "phi.policyDetails",
    name: "Private health insurance policy details",
    section: "medicare-and-phi",
    form: "main",
    inScope: true,
    note: "From the PHI tax statement — premiums eligible for rebate, rebate received, benefit code.",
  },

  // --- Spouse details & income tests ------------------------
  {
    code: "spouse.details",
    name: "Spouse details — married or de facto",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "Spouse name / DOB / estimated taxable income / days with private hospital cover (FR-1). Income marked 'estimated'.",
  },
  {
    code: "IT1",
    name: "Total reportable fringe benefits amounts",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "From the income statement. Feeds the FR-23 income-test figures.",
  },
  {
    code: "IT2",
    name: "Reportable employer superannuation contributions",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "From the income statement. Feeds the FR-23 income-test figures.",
  },
  {
    code: "IT3",
    name: "Tax-free government pensions or benefits",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "Usually nil in scope; captured for completeness of the income tests.",
  },
  {
    code: "IT4",
    name: "Target foreign income",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: false,
    note: "Any amount indicates foreign income → FR-20.",
  },
  {
    code: "IT5",
    name: "Net financial investment loss",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "Treated as zero for v1 scope (FR-23).",
  },
  {
    code: "IT6",
    name: "Net rental property loss",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "The net rental loss from the rental schedule — added back into the FR-23 income-test figures.",
  },
  {
    code: "IT7",
    name: "Child support you paid",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "User-entered; affects some income-test calculations.",
  },
  {
    code: "IT8",
    name: "Number of dependent children",
    section: "spouse-and-income-tests",
    form: "main",
    inScope: true,
    note: "Drives the family Medicare levy / surcharge / rebate thresholds.",
  },

  // --- Estimate --------------------------------------------------
  {
    code: "estimate.totalTaxWithheld",
    name: "Total tax withheld",
    section: "estimate",
    form: "main",
    inScope: true,
    note: "Computed — sum of PAYG withheld + TFN amounts withheld.",
  },
  {
    code: "estimate.result",
    name: "Estimated refund or amount owing",
    section: "estimate",
    form: "main",
    inScope: true,
    note: "Computed by the engine (FR-12). An estimate, not the ATO's assessment.",
  },
];

// Item 21 rental property schedule (FR-24). Paper labels: P (gross rent),
// Q (interest deductions), F (capital works deductions), U (other rental
// deductions), Net rent = P − (Q + F + U). myTax breaks label U into the
// individual expense categories below.
const RENTAL_SCHEDULE: readonly RentalScheduleLabel[] = [
  {
    key: "grossRent",
    name: "Gross rent",
    kind: "income",
    paperLabel: "P",
    inScope: true,
    note: "Rent received / entitled to for the year, from the managing agent's annual statement.",
  },
  {
    key: "otherRentalIncome",
    name: "Other rental-related income",
    kind: "income",
    paperLabel: "P",
    inScope: true,
    note: "Bond money retained, insurance payout for lost rent, reimbursed expenses.",
  },
  {
    key: "interestOnLoans",
    name: "Interest on loan(s)",
    kind: "deduction",
    paperLabel: "Q",
    inScope: true,
    note: "From the lender's annual interest summary.",
  },
  {
    key: "capitalWorks",
    name: "Capital works deductions (Division 43)",
    kind: "deduction",
    paperLabel: "F",
    inScope: true,
    note: "2.5% (or 4%) of eligible construction cost, from the quantity surveyor's schedule (FR-3).",
  },
  {
    key: "declineInValue",
    name: "Decline in value of depreciating assets (Division 40)",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "From the quantity surveyor's schedule. Second-hand asset rules apply.",
  },
  {
    key: "borrowingExpenses",
    name: "Borrowing expenses",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "Loan establishment costs spread over 5 years (or the loan term). User enters the year's portion (Q25) — the tool does not track the amortisation.",
  },
  {
    key: "advertising",
    name: "Advertising for tenants",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "bodyCorporate",
    name: "Body corporate fees and charges",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "Owner-paid — user-entered if not on the agent statement.",
  },
  {
    key: "cleaning",
    name: "Cleaning",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "councilRates",
    name: "Council rates",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "gardeningLawn",
    name: "Gardening and lawn mowing",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "insurance",
    name: "Insurance",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "Landlord / building / contents. Owner-paid — user-entered if not on the agent statement.",
  },
  {
    key: "landTax",
    name: "Land tax",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "Owner-paid — user-entered if not on the agent statement.",
  },
  {
    key: "legalFees",
    name: "Legal expenses",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "Excludes acquisition, sale and borrowing costs.",
  },
  {
    key: "pestControl",
    name: "Pest control",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "agentFees",
    name: "Property agent fees and commissions",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "Management and letting fees, from the agent's annual statement.",
  },
  {
    key: "repairsAndMaintenance",
    name: "Repairs and maintenance",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
    note: "A single line over $1,000 (Q25) must be confirmed a genuine repair, not a capital improvement (FR-13, FR-24).",
  },
  {
    key: "stationeryPhonePostage",
    name: "Stationery, telephone and postage",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "travelExpenses",
    name: "Travel expenses",
    kind: "deduction",
    paperLabel: "U",
    inScope: false,
    note: "Travel to a residential rental property is not deductible (since 1 July 2017). Kept in the taxonomy so a claimed amount is caught.",
  },
  {
    key: "waterCharges",
    name: "Water charges",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "sundryExpenses",
    name: "Sundry rental expenses",
    kind: "deduction",
    paperLabel: "U",
    inScope: true,
  },
  {
    key: "netRent",
    name: "Net rent",
    kind: "computed",
    paperLabel: "net",
    inScope: true,
    note: "= gross rent + other rental income − (interest + capital works + other rental deductions). May be a loss; flows to item 21 and into taxable income (FR-8) and the FR-23 add-back.",
  },
];

export const taxonomy202526: LabelTaxonomy = {
  source: SRC.itr,
  verifiedOn: "2026-09-04",
  note: `Rental schedule sub-labels compiled from ${SRC.suppRent} and the myTax 2026 rent screen (${SRC.mytax}). Confirm the granular expense list against the live myTax rent entry screen.`,
  myTaxSectionOrder: MYTAX_SECTION_ORDER,
  labels: LABELS,
  rentalSchedule: RENTAL_SCHEDULE,
};
